<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
$form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu");
	var g = document.getElementById("menu_group");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body {
	padding: 0 !important;
}

.col-md-12 {
	padding: 0 !important;
}

input[type=checkbox] {
	*opacity: 1 !important;
}

.form-group {
	padding: 0;
}

.form-horizontal .form-group {
	margin: 0;
	padding: 10px 0;
}
-->
</style>
<div class="main-wrapper">
	<form role="form" class="form-horizontal" id="form"
		enctype="multipart/form-data" method="post">
		<!-- start: MAIN CONTAINER -->
		<div class="main-container inner">
			<!-- start: PAGE -->
			<div class="main-content">
				<!-- end: SPANEL CONFIGURATION MODAL FORM -->
				<div class="container">
					<!-- start: BREADCRUMB -->
					<div class="row" style="margin-top: 5px;"></div>
					<!-- end: BREADCRUMB -->
					<div class="col-md-12">
						<div class="errorHandler alert alert-danger no-display">
							<i class="fa fa-times-sign"></i> You have some form errors.
							Please check below.
						</div>
						<div class="successHandler alert alert-success no-display">
							<i class="fa fa-ok"></i> Your form validation is successful!
						</div>
					</div>
					<!-- start: PAGE CONTENT -->
					<div class="row">
						<div class="col-sm-12">
							<!-- start: TEXT FIELDS PANEL -->
							<div class="panel panel-white">
								<div class="panel-heading">
									<div class="" style="float: right;">
										<button type="submit" class="btn btn-primary">
											<i class="fa fa-edit"></i> Eidt
										</button>
										<button type="button" class="btn btn-primary panel-refresh">
											<i class="fa fa-save"></i> Save
										</button>
										<button type="button" class="btn btn-primary">
											<i class="glyphicon glyphicon-log-in"></i> Save New
										</button>
										<a href="<?php echo $this->baseUrl();?>/menu"><button
												type="button" class="btn btn-red">
												<i class="fa fa-times"></i> Eixt
											</button></a>
									</div>
								</div>
									<div class="panel-body">
											<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-4 control-label">
															<?php echo $tr->translate("ITEM_CODE")?>
														</label>
													<div class="col-sm-8">
															<?php echo $form->getElement('item_code');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<div class="col-sm-12">
															<?php echo $form->getElement('qty_handow');?>
														</div>
												</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
												<div class="form-group col-sm-6">
													<label class="col-sm-4 control-label">
															<?php echo $tr->translate("WHEREHOUSE_ID")?>
														</label>
													<div class="col-sm-8">
															<?php echo $form->getElement('wherehouse_id');?>
														</div>
		
												</div>
												<div class="form-group col-sm-6">
													<div class="col-sm-12">
															<?php echo $form->getElement('handow');?>
														</div>
												</div>
											</div>
									</div>
									<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-12">
											<div class="col-sm-12">
												<div class="tabbable" id="tabShow">
													<ul id="myTab" class="nav nav-tabs">
														<li class="active"><a href="#myTab_example1"
															data-toggle="tab"> <i class="green fa fa-gear"></i> <?php echo $tr->translate("General Information")?>
																</a></li>
														<li><a href="#myTab_example2" data-toggle="tab"> <i
																class="green fa fa-gear"></i> <?php echo $tr->translate("Cost-usage")?>
																</a></li>
														<li><a href="#myTab_example3" data-toggle="tab"> <i
																class="green fa fa-gear"></i> <?php echo $tr->translate("note")?>
																</a></li>
														
													</ul>
													<div class="tab-content">
														<div class="tab-pane fade in active" id="myTab_example1">
														<div class="form-group">
															<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("SUPER_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('product_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background');?>
																	</div>
																  </div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("PART_NUMBER")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('stock_unit_id');?>
																	</div>
																	
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("STOCK_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('puchase_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background2');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("PURCHASE_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('sale_id');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-2 control-label" for="form-field-1">
																			<?php echo $tr->translate("SALE_UNIT_ID")?>
																	</label>
																	<div class="col-sm-4">
																			<?php echo $form->getElement('part_number');?>
																	</div>
																	<div class="col-sm-6">
																			<?php echo $form->getElement('background3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("LEAD_TIME")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_POIN")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																</div>
																 
													    	</div>
													    	<div class="form-group">
																 <div class="form-group col-sm-12">
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_QTY")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																	<label class="col-sm-1 control-label" for="form-field-1">
																			<?php echo $tr->translate("ORDER_QTY2")?>
																	</label>
																	<div class="col-sm-5">
																			<?php echo $form->getElement('demo3');?>
																	</div>
																</div>
																 
													    	</div>
														</div>
														</div>
														<div class="tab-pane fade" id="myTab_example2">
															<div class="form-group">
																<div class="form-group">
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("STANDART_COST")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_Usage_value")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_usage_value');?>
																		</div>
																	 </div>
													    		</div>
													    		<div class="form-group">
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("QTY_ONHAND")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('demo3');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_Usage_qty")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_usage_qty');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("AVERAGE_COST")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('average_cost');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_sale_value")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_sale_value');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_RECEIVE_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_receive_date');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("PTD_sale_qty")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('ptd_sale_qty');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_SALE_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_sale_date');?>
																		</div>
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_COUNT_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_count_date');?>
																		</div>
																	 </div>
																	 <div class="form-group col-sm-12">
																		<label class="col-sm-2 control-label" for="form-field-1">
																				<?php echo $tr->translate("LAST_ORDER_DATE")?>
																		</label>
																		<div class="col-sm-4">
																				<?php echo $form->getElement('last_order_date');?>
																		</div>
																	 </div>
													    		</div>
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example3">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example4">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example5">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example6">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example7">
															<div class="form-group">
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example8">
															<div class="form-group">
															</div>
														</div>
													</div>
													<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>ITEM_CODE</th>
																<th>BRANCH</th>
																<th class="hidden-xs">DISCRIPTION</th>
																<th>SECOND_LANGAUGE</th>
																<th>AVG.COST</th>
																<th>HANDON</th>
																<th>STOCK_UNIT</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>001</td>
																<td> 001</td>
																<td>tiger can</td>
																<td></td>
																<td>1.000</td>
																<td> 199.000</td>
																<td>CAN</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
				<!-- end: MAIN CONTAINER -->
				<div id="readNote">
					<div class="noteWrap col-md-8 col-md-offset-2">
						<div class="panel panel-note">
							<div class="e-slider owl-carousel owl-theme">
								<div class="item">
									<div class="panel-heading"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>