<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu_custom");
	var g = document.getElementById("menu_customers");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body{padding: 0 !important;}
.col-md-12{padding: 0 !important;}
input[type=checkbox]{*opacity: 1!important;}
.form-group{padding: 0;}
.form-horizontal .form-group{margin: 0;padding:10px 0;}
-->
</style>
<div class="main-wrapper">
	<form role="form"  class="form-horizontal" id="form" enctype="multipart/form-data" method="post">
			<!-- start: MAIN CONTAINER -->
			<div class="main-container inner">
				<!-- start: PAGE -->
				<div class="main-content">
					<!-- end: SPANEL CONFIGURATION MODAL FORM -->
					<div class="container">
						<!-- start: BREADCRUMB -->
						<div class="row" style="margin-top: 5px;">
						</div>
						<!-- end: BREADCRUMB -->
						<div class="col-md-12">
							<div class="errorHandler alert alert-danger no-display">
								<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
							</div>
							<div class="successHandler alert alert-success no-display">
								<i class="fa fa-ok"></i> Your form validation is successful!
							</div>
						</div>
						<!-- start: PAGE CONTENT -->
						<div class="row">
							<div class="col-sm-12">
								<!-- start: TEXT FIELDS PANEL -->
								<div class="panel panel-white">
									<div class="panel-heading">
										<div class="" style="float: right;">
											<button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</button>
											<button type="button" class="btn btn-primary panel-refresh"><i class="fa fa-save"></i> Save</button>
											<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-log-in"></i> Save New</button>
											<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn btn-red"><i class="fa fa-times"></i> Exit</button></a>
										</div>
									</div>
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CUSTOMER_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('customer_id');?> 
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("APPLY_TO_COMPANY")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('apply');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("COMPANY")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('company');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CURRENT_BALANCE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('current');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("SECOND_LANGUAGE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('second_language');?> 
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CONTACT_NAME")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('contact');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("YTD_SALE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('sale');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("MOBILE_PHONE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('mobile');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("AVAILABLE_CREDIT")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('credit');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CUSTOMER_GROUP_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('customer_group');?>
												</div>
											</div>
											<div class="form-group col-sm-6" >
													<label class="col-sm-4 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("IN_ACTIVE")?> <span class="symbol required"></span>
													</label>
													<div class="col-sm-2">
														<label class="checkbox-inline" >
															<?php echo $form->getElement('active');?>
														</label>													
													</div>
													<label class="col-sm-4 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("ON_HOLD")?> <span class="symbol required"></span>
													</label>
													<div class="col-sm-2">
														<label class="checkbox-inline">
															<?php echo $form->getElement('hold');?>
														</label>													
													</div>
										   </div>
										<div class="col-sm-12" style="padding: 0; margin-top:-55px;">
											<div class="form-group col-sm-6">
											</div>
 											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("IMAGE")?>  <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<div class="fileupload fileupload-new" data-provides="fileupload">
														<div class="fileupload-new thumbnail"><img src="" alt=""/>
														</div>
														<div class="fileupload-preview fileupload-exists thumbnail"></div>
														<div>
															<span class="btn btn btn-primary btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> Change</span>
																<input type="file" name="photo">
															</span>
															<a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
																<i class="fa fa-times"></i> Remove
															</a>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group">
												<div class="col-sm-12">
													<div class="tabbable" style="" id="tabShwo">
														<ul id="myTab" class="nav nav-tabs">
															<li class="active">
																<a href="#myTab_example1" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("GENERAL_INFORMATION & ADDRESS")?> <span class="symbol required"></span>
																</a>
															</li>
															<li>
																<a href="#myTab_example2" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("SHOW_INFORMATION")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example4" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("CUSTOMER_HISTORY")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example5" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("MEMBERSHIP")?>
																</a>
															</li>
															<li>
																<a href="#myTab_example3" data-toggle="tab">
																	<i class="green fa fa-gear"></i> <?php echo $tr->translate("NOTE")?>
																</a>
															</li>
														</ul>
													<div class="tab-content">
														<div class="tab-pane fade in active" id="myTab_example1">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("PHONE_2")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('phone_2');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("TITLE")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('title');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("ADDRESS_2")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('address_2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("CITY")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('city');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("COUNTRY")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('country');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("FAX_2")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('fax_2');?>
																	</div>
																</div>
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>																											
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example2">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example4">
															<div class="form-group">
																<div class="form-group">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														<div class="tab-pane fade" id="myTab_example5">
															<div class="form-group">
																<div class="form-group ">
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("EMAIL")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('email');?>
																	</div>
																	<label class="col-sm-2 control-label" for="form-field-1">
																		<?php echo $tr->translate("WEB_PAGE")?> <span class="symbol required"></span>
																	</label>
																	<div class="col-sm-4">
																		<?php echo $form->getElement('web');?>
																	</div>
																</div>		
															</div>
														</div>
														
														<div class="tab-pane fade" id="myTab_example3">
															<div class="form-group">
																<div class="form-group">
																	<div class="col-sm-12">
																		<?php echo $tr->translate("NOTED")?> 
																	</div>
																	<div class="col-sm-12">
																		<?php echo $form->getElement('noted');?>
																	</div>
																</div>	
															</div>
														</div>
													</div>
												</div>
											</div>
											
										   <div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("CUSTOMER_ID")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("COMPANY")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("CONTACT_NAME")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("PHONE")?></th>
															</tr>
														</thead>
														<tbody>	
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							</div>
			<!-- end: MAIN CONTAINER -->
							<div id="readNote">
							<div class="noteWrap col-md-8 col-md-offset-2">
								<div class="panel panel-note">
								<div class="e-slider owl-carousel owl-theme">
									<div class="item">
										<div class="panel-heading">
										</div>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>