<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu_custom");
	var g = document.getElementById("menu_rate");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body{padding: 0 !important;}
.col-md-12{padding: 0 !important;}
input[type=checkbox]{*opacity: 1!important;}
.form-group{padding: 0;}
.form-horizontal .form-group{margin: 0;padding:10px 0;}
-->
</style>
<div class="main-wrapper">
	<form role="form"  class="form-horizontal" id="form" enctype="multipart/form-data" method="post">
			<!-- start: MAIN CONTAINER -->
			<div class="main-container inner">
				<!-- start: PAGE -->
				<div class="main-content">
					<!-- end: SPANEL CONFIGURATION MODAL FORM -->
					<div class="container">
						<!-- start: BREADCRUMB -->
						<div class="row" style="margin-top: 5px;">
						</div>
						<!-- end: BREADCRUMB -->
						<div class="col-md-12">
							<div class="errorHandler alert alert-danger no-display">
								<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
							</div>
							<div class="successHandler alert alert-success no-display">
								<i class="fa fa-ok"></i> Your form validation is successful!
							</div>
						</div>
						<!-- start: PAGE CONTENT -->
						<div class="row">
							<div class="col-sm-12">
								<!-- start: TEXT FIELDS PANEL -->
								<div class="panel panel-white">
									<div class="panel-heading">
										<div class="" style="float: right;">
											<button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Eidt</button>
											<button type="button" class="btn btn-primary panel-refresh"><i class="fa fa-save"></i> Save</button>
											<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-log-in"></i> Save New</button>
											<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn btn-red"><i class="fa fa-times"></i> Eixt</button></a>
										</div>
									</div>
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CUSTOMER_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('customer_id');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("GENERAL")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('general');?>
												</div>
											</div>
								
										<div class="col-sm-12" style="padding: 0;">
											
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("IMAGE")?>  <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<div class="fileupload fileupload-new" data-provides="fileupload">
														<div class="fileupload-new thumbnail"><img src="" alt=""/>
														</div>
														<div class="fileupload-preview fileupload-exists thumbnail"></div>
														<div>
															<span class="btn btn btn-primary btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> Change</span>
																<input type="file" name="photo">
															</span>
															<a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
																<i class="fa fa-times"></i> Remove
															</a>
														</div>
													</div>
												</div>
											</div>
										</div>
										
										<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("NUM")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("MENU_GROUP_CODE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("DESCRIPTION")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_ONE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("LANG_TWO")?></th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td style="text-align: center;">1</td>
																<td>Amaya</td>
																<td class="hidden-xs">W3C,
																INRIA</td>
																<td>Free</td>
																<td class="hidden-xs">W3C</td>
															</tr>
															<tr>
																<td style="text-align: center;">2</td>
																<td>AOL Explorer</td>
																<td class="hidden-xs">America Online, Inc</td>
																<td>Free</td>
																<td class="hidden-xs">Proprietary</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							</div>
			<!-- end: MAIN CONTAINER -->
							<div id="readNote">
							<div class="noteWrap col-md-8 col-md-offset-2">
								<div class="panel panel-note">
								<div class="e-slider owl-carousel owl-theme">
									<div class="item">
										<div class="panel-heading">
										</div>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>