<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu_custom");
	var g = document.getElementById("menu_currency");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body{padding: 0 !important;}
.col-md-12{padding: 0 !important;}
input[type=checkbox]{*opacity: 1!important;}
.form-group{padding: 0;}
.form-horizontal .form-group{margin: 0;padding:10px 0;}
-->
</style>
<div class="main-wrapper">
	<form role="form"  class="form-horizontal" id="form" enctype="multipart/form-data" method="post">
			<!-- start: MAIN CONTAINER -->
			<div class="main-container inner">
				<!-- start: PAGE -->
				<div class="main-content">
					<!-- end: SPANEL CONFIGURATION MODAL FORM -->
					<div class="container">
						<!-- start: BREADCRUMB -->
						<div class="row" style="margin-top: 5px;">
						</div>
						<!-- end: BREADCRUMB -->
						<div class="col-md-12">
							<div class="errorHandler alert alert-danger no-display">
								<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
							</div>
							<div class="successHandler alert alert-success no-display">
								<i class="fa fa-ok"></i> Your form validation is successful!
							</div>
						</div>
						<!-- start: PAGE CONTENT -->
						<div class="row">
							<div class="col-sm-12">
								<!-- start: TEXT FIELDS PANEL -->
								<div class="panel panel-white">
									<div class="panel-heading">
										<div class="" style="float: right;">
											<button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</button>
											<button type="button" class="btn btn-primary panel-refresh"><i class="fa fa-save"></i> Save</button>
											<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-log-in"></i> Save New</button>
											<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn btn-red"><i class="fa fa-times"></i> Exit</button></a>
										</div>
									 
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CURRENCY_CODE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('currency_code');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CURRENCY_TEXT")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('currency_text');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("CURRENCY_SYMBLE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('currency_sy');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("DECIMAL_PLACE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('decimal');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("EXCHANGE_RATE")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('exchange');?>
												</div>
											</div>
											
											
											<div class="form-group col-sm-6">
													<label class="col-sm-5 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("CURRENCY_BASE")?> <span class="symbol required"></span>
													</label>
													<div class="col-sm-1">
														<label class="checkbox-inline" >
															<?php echo $form->getElement('currency');?>
														</label>													
													</div>
													<label class="col-sm-4 control-label" for="form-field-1" style="margin-top: 7px;">
														<?php echo $tr->translate("BASE_CURRENCY")?> <span class="symbol required"></span>
													</label>
													<div class="col-sm-2">
														<label class="checkbox-inline">
															<?php echo $form->getElement('base');?>
														</label>	
														
																										
													</div>
										   </div>
										   
										<div class="col-sm-12" style="padding: 0;">CURRENCY_LIST
											<div class="form-group">
												<div class="col-sm-12">
													<div class="tabbable" style="" id="tabShwo">
														
												    <div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
														 <div class="panel panel-white">
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("CURRENCY_CODE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("TEXT")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("SYMBLE")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("DECIMAL_PLACE")?></th>
															</tr>
														</div>
														</thead>
														<tbody>	
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							</div>
			<!-- end: MAIN CONTAINER -->
							<div id="readNote">
							<div class="noteWrap col-md-8 col-md-offset-2">
								<div class="panel panel-note">
								<div class="e-slider owl-carousel owl-theme">
									<div class="item">
										<div class="panel-heading">
										</div>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>