<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu_setting");
	var g = document.getElementById("menu_system");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body{padding: 0 !important;}
.col-md-12{padding: 0 !important;}
input[type=checkbox]{*opacity: 1!important;}
.form-group{padding: 0;}
.form-horizontal .form-group{margin: 0;padding:10px 0;}
-->
</style>
<div class="main-wrapper">
	<form role="form"  class="form-horizontal" id="form" enctype="multipart/form-data" method="post">
			<!-- start: MAIN CONTAINER -->
			<div class="main-container inner">
				<!-- start: PAGE -->
				<div class="main-content">
					<!-- end: SPANEL CONFIGURATION MODAL FORM -->
					<div class="container">
						<!-- start: BREADCRUMB -->
						<div class="row" style="margin-top: 5px;">
						</div>
						<!-- end: BREADCRUMB -->
						<div class="col-md-12">
							<div class="errorHandler alert alert-danger no-display">
								<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
							</div>
							<div class="successHandler alert alert-success no-display">
								<i class="fa fa-ok"></i> Your form validation is successful!
							</div>
						</div>
						<!-- start: PAGE CONTENT -->
						<div class="row">
							<div class="col-sm-12">
								<!-- start: TEXT FIELDS PANEL -->
								<div class="panel panel-white">
									<div class="panel-heading">
										<div class="" style="float: right;">
											<button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</button>
											<button type="button" class="btn btn-primary panel-refresh"><i class="fa fa-save"></i> Save</button>
											<button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-log-in"></i> Save New</button>
											<a href="<?php echo $this->baseUrl();?>/menu"><button type="button" class="btn btn-red"><i class="fa fa-times"></i> Exit</button></a>
										</div>
									</div>
									<div class="panel-body">
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_ID")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_id');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_NAME")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_name');?>
												</div>
											</div>
											
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("USER_NAME2")?> <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<?php echo $form->getElement('user_name2');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label">
													<?php echo $tr->translate("GENDER")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('gender');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("LANGUAGE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('language');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("USER_LEVEL")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('user_level');?>
												</div>
											</div>
												
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("REPORT_LANGUAGE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('report_language');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("ACCESS_TO_COMPANY")?> <span class="symbol required"></span>
												</label>
					
												<div class="col-sm-8">
													<?php echo $form->getElement('access_to_company');?> 
												</div>
											</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("DEFAULT_COMPANY")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('default_company');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("PASSWORD")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('password');?>
												</div>
											</div>
											</div>
											<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("CONFIRM_PASSWORD")?> <span class="symbol required"></span>
												</label>
											
												<div class="col-sm-8">
													<?php echo $form->getElement('confirm_password');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("SALEPERSON")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('sale');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("USER_GROUP_NAME")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('usergroup');?>
												</div>
											</div>
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("LOGIN_GROUP_ID")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('login');?>
												</div>
											</div>
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("PRICE_LEVEL")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('price');?>
												</div>
											</div>
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("AUTO_LOG_OFF")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('autolock');?>
												</div>
											</div>
										<div class="col-sm-12" style="padding: 0;">	
											<div class="form-group col-sm-6">
											    <label class="col-sm-8 control-label" for="form-field-1" style="margin-top: -3px;">
													<?php echo $tr->translate("USER_MUST_CHANGE_PASSWORD_AT_NEXT_LOG_ON")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-4">
													<?php echo $form->getElement("usermust");?>
												</div>
											</div>
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1" style="margin-top: -3px;">
													<?php echo $tr->translate("ACTIVE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('active');?>
												</div>
											</div>
										</div>
									<div class="col-sm-12" style="padding: 0;">
											<div class="form-group col-sm-6">
											    <label class="col-sm-8 control-label" for="form-field-1" style="margin-top: -3px;">
													<?php echo $tr->translate("USER_CANNOT_CHANGE_PASSWORD")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-4">
													<?php echo $form->getElement('userpwd');?>
												</div>
											</div>
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1" style="margin-top: -4px;">
													<?php echo $tr->translate("USER_SCHEDULE_LOG_IN")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('userschedule');?>
												</div>
											</div>
										</div>
										<div class="col-sm-12" style="padding: 0;">
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("NOTE")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('note');?>
												</div>
											</div>
											
											<div class="form-group col-sm-6">
											    <label class="col-sm-4 control-label" for="form-field-1" >
													<?php echo $tr->translate("ROLE_DESCRIPTION")?> <span class="symbol required"></span>
												</label>
												
												<div class="col-sm-8">
													<?php echo $form->getElement('des');?>
												</div>
											</div>
											
											
											</div>
											<div class="form-group col-sm-6" >
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("IMAGE")?>  <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<div class="fileupload fileupload-new" data-provides="fileupload" >
														<div class="fileupload-new thumbnail" ><img src="" alt=""/>
														</div>
														<div class="fileupload-preview fileupload-exists thumbnail"></div>
														<div>
															<span class="btn btn-primary btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> Change</span>
																<input type="file" name="photo">
															</span>
															<a href="#" class="fileupload-exists btn btn-primary" data-dismiss="fileupload">
																<i class="fa fa-times"></i> Remove
															</a>
														</div>
													</div>
												</div>
											</div>
										</div>
															
										<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr style="text-align: center;">
																<th style="text-align: center;"><?php echo $tr->translate("USER_ID")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("USER_NAME")?></th>
																<th style="text-align: center;"><?php echo $tr->translate("USER_NAME2")?></th>
															</tr>
														</thead>
														<tbody>
															
															<tr>
																<td style="text-align: center;">2</td>
																<td>AOL Explorer</td>
																<td class="hidden-xs">America Online, Inc</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							</div>
			<!-- end: MAIN CONTAINER -->
							
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>