<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<!-- start: HEAD -->
	<head>
		<title>Resturant</title>
		<!-- start: META -->
		<meta charset="utf-8" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta content="" name="description" />
		<meta content="" name="author" />
		<!-- end: META -->
		<!-- start: MAIN CSS -->
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/iCheck/skins/all.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/animate.css/animate.min.css">
		<!-- end: MAIN CSS -->
		<!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/summernote/dist/summernote.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/toastr/toastr.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-select/bootstrap-select.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/DataTables/media/css/DT_bootstrap.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
		<!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
		<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/select2/select2.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/datepicker/css/datepicker.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.css">
		<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- start: CORE CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/styles.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/styles-responsive.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/plugins.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/assets/css/print.css" type="text/css" media="print"/>
		<!-- end: CORE CSS -->
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/favicon.ico" />

		<style type="text/css"> dt{display: none;}</style>
	</head>
	<!-- end: HEAD -->
    <!-- <body class="soria">
    <body class="soria"> -->
    <body>
    	<?php echo $this->render('header.phtml')?>
    		<!-- end: SLIDING BAR -->
		<div class="main-wrapper">
			<?php echo $this->render('header-bottom.phtml')?>
	    	<?php echo $this->render('menuleft.phtml')?>
	    	<?php echo $this->render('menuright.phtml')?>
	        <?php echo $this->layout()->content; ?>
	        <?php echo $this->render('footer.phtml')?>
        </div>
        		<!-- start: MAIN JAVASCRIPTS -->
		<!--[if lt IE 9]>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/respond.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/excanvas.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/plugins/jQuery/jquery-1.11.1.min.js"></script>
		<![endif]-->
		<!--[if gte IE 9]><!-->
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
		<!--<![endif]-->
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/iCheck/jquery.icheck.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/moment/min/moment.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootbox/bootbox.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery.appear/jquery.appear.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/velocity/jquery.velocity.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
		<!-- end: MAIN JAVASCRIPTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/toastr/toastr.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/truncate/jquery.truncate.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/summernote/dist/summernote.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/js/subview.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/js/subview-examples.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/autosize/jquery.autosize.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/select2/select2.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-colorpicker/js/commits.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/ckeditor/ckeditor.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/ckeditor/adapters/jquery.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/js/form-elements.js"></script>
		<script src="<?php echo $this->baseUrl()?>/assets/js/form-validation.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<!-- END PAGE LEVEL SCRIPTS -->
		<script src="<?php echo $this->baseUrl() . '/assets/plugins/validationengine/js/jquery.validationEngine.js'?>"></script>
		<script src="<?php echo $this->baseUrl() . '/assets/plugins/validationengine/js/languages/jquery.validationEngine-en.js'?>"></script>
		<script src="<?php echo $this->baseUrl() . '/assets/plugins/jquery-validation-1.11.1/dist/jquery.validate.min.js'?>"></script>
		<script src="<?php echo $this->baseUrl() . '/assets/js/validationInit.js'?>"></script>
		<!-- start: CORE JAVASCRIPTS  -->
		<script src="<?php echo $this->baseUrl()?>/assets/js/main.js"></script>
		<!-- end: CORE JAVASCRIPTS  -->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/plugins/select2/select2.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl()?>/assets/js/table-data.js"></script>
		
		<script>
			jQuery(document).ready(function() {
				Main.init();
				SVExamples.init();
				FormElements.init();
				TableData.init();
				FormValidator.init();
			});
		</script>		
    </body>
</html>
