<?php 	$tr=Application_Form_FrmLanguages::getCurrentlanguage();?> 
<?php $request=Zend_Controller_Front::getInstance()->getRequest(); $module=$request->getModuleName();?>
<script type="text/javascript">
<!--
	function OpenClass(){
		window.location = "<?php echo $this->baseUrl();?>/menu";
	}
	
//-->
</script>
		<nav id="pageslide-left" class="pageslide inner">
				<div class="navbar-content">
					<!-- start: SIDEBAR -->
					<div class="main-navigation left-wrapper transition-left">
						<div class="navigation-toggler hidden-sm hidden-xs">
							<a href="#main-navbar" class="sb-toggle-left">
							</a>
						</div>
						<div class="border-top padding-horizontal-10 block">
							<div class="inline-block" style="">
								<a href="<?php echo $this->baseUrl();?>/dashboard"><i class="fa fa-home"></i> <span class="title"> Resturant Management </span> </a>
							</div>
							<div class="inline-block">
								<a class="btn user-options sb_toggle">
									<i class="fa fa-cog"></i>
								</a>
							</div>
						</div>
						<!-- start: MAIN NAVIGATION MENU -->
						<ul class="main-navigation-menu">
							<li>
								
							</li>
							<li id="menu">
								<a onclick="OpenClass()"><i class="fa fa-desktop"></i> <span class="title"> Menu Management </span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li id="menu_group">
										<a href="<?php echo $this->baseUrl()?>/menu/group">
											<?php echo $tr->translate("MENU_GROUP")?>
										</a>
									
									</li>
									<li id="menu_item">
										<a href="<?php echo $this->baseUrl()?>/menu/item">
											<?php echo $tr->translate("MENU_ITEM")?>
										</a>
									</li>
									<li id="menu_arrangement">
										<a href="<?php echo $this->baseUrl()?>/menu/arrangement">
											<?php echo $tr->translate("MENU_ARRANGEMENT")?>
										</a>
									</li>
									<li id="menu_combo">
										<a href="<?php echo $this->baseUrl()?>/menu/combo">
											<?php echo $tr->translate("COMBO_MASTER")?>
										</a>
									</li>
									<li id="menu_recipe">
										<a href="<?php echo $this->baseUrl()?>/menu/recipe">
											<?php echo $tr->translate("RECIPE")?>
										</a>
									</li>
									<li id="menu_discount">
										<a href="<?php echo $this->baseUrl()?>/menu/discount">
											<?php echo $tr->translate("DISCOUNT")?>
										</a>
									</li>
									<li id="menu_houre">
										<a href="<?php echo $this->baseUrl()?>/menu/happyhour">
											<?php echo $tr->translate("HAPPY_HOUR")?>
										</a>
									</li>
								</ul>
							</li>
							<li id="menu_table">
								<a onclick="OpenClassTable()" href="javascript:void(0)"><i class="fa fa-th-large"></i> <span class="title"> Tables Management</span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li id="menu_customer">
										<a href="<?php echo $this->baseUrl()?>/table/customer">
											<?php echo $tr->translate("APPLY_customer")?>
										</a>
									</li>
									<li id="menu_tables">
										<a href="<?php echo $this->baseUrl()?>/table/tables">
											<?php echo $tr->translate("TABLES")?>
										</a>
									</li>
									<li id="menu_arrangement">
										<a href="<?php echo $this->baseUrl()?>/table/arrangement">
											<?php echo $tr->translate("TABLE_ARRANGEMENT")?>
										</a>
									</li>
									<li>
										<a href="table_data.html">
											<span class="title">Advanced Data Tables</span>
										</a>
									</li>
									<li>
										<a href="table_export.html">
											<span class="title">Table Export</span>
										</a>
									</li>
								</ul>
							</li>
							<li id="menu_inventory">
								<a href="javascript:void(0)"><i class="fa fa-cubes"></i> <span class="title"> Inventory Management </span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li id="menu_wherehouse">
										<a href="<?php echo $this->baseUrl()?>/inventory/wherehouse">
											<?php echo $tr->translate("WHERE_HOUSE")?>
										</a>
									</li>
									<li id="menu_measure">
										<a href="<?php echo $this->baseUrl()?>/inventory/measure">
											<?php echo $tr->translate("MEASURE")?>
										</a>
									</li>
									<li id="menu_productlind">
										<a href="<?php echo $this->baseUrl()?>/inventory/productlind">
											<?php echo $tr->translate("PRODUCTLIND")?>
										</a>
									</li>
									<li id="menu_supplier">
										<a href="<?php echo $this->baseUrl()?>/inventory/supplier">
											<?php echo $tr->translate("SUPPLIER")?>
										</a>
									</li>
									<li>
										<a href="form_x_editable.html">
											<span class="title">Form X-editable</span>
										</a>
									</li>
									<li>
										<a href="form_image_cropping.html">
											<span class="title">Image Cropping</span>
										</a>
									</li>
									<li>
										<a href="form_multiple_upload.html">
											<span class="title">Multiple File Upload</span>
										</a>
									</li>
									<li>
										<a href="form_dropzone.html">
											<span class="title">Dropzone File Upload</span>
										</a>
									</li>
								</ul>
							</li>
							<li id="menu_custom">
								<a href="javascript:void(0)"><i class="fa fa-users"></i> <span class="title">Customer Management</span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li id="menu_deposit">
										<a href="<?php echo $this->baseUrl()?>/customer/deposit">
											<?php echo $tr->translate("APPLY_CREDIT_DEPOSIT")?>
										</a>
									</li>
									<li id="menu_credit">
										<a href="<?php echo $this->baseUrl()?>/customer/credit">
											<?php echo $tr->translate("CREDIT CARD")?>
										</a>
									</li>
									<li id="menu_customer">
										<a href="<?php echo $this->baseUrl()?>/customer/customer">
											<?php echo $tr->translate("CUSTOMER")?>
										</a>
									</li>
									<li id="menu_currency">
										<a href="<?php echo $this->baseUrl()?>/customer/currency">
											<?php echo $tr->translate("CURRENCY")?>
										</a>
									</li>
									<li id="menu_curtype">
										<a href="<?php echo $this->baseUrl()?>/customer/curtype">
											<?php echo $tr->translate("CURRENCY TYPE")?>
										</a>
									</li>
									<li id="menu_cash">
										<a href="<?php echo $this->baseUrl()?>/customer/cash">
											<?php echo $tr->translate("ENTER CASH DEPOSIT")?>
										</a>
									</li>
									<li id="menu_invoice">
										<a href="<?php echo $this->baseUrl()?>/customer/invoice">
											<?php echo $tr->translate("ENTER INVOICE PAYMENT")?>
										</a>
									<li>
									<li id="menu_rate">
										<a href="<?php echo $this->baseUrl()?>/customer/rate">
											<?php echo $tr->translate("EXCHANGE RATE")?>
										</a>
									</li>
									<li id="menu_sale">
										<a href="<?php echo $this->baseUrl()?>/customer/sale">
											<?php echo $tr->translate("SALE REPRESENTATIVE")?>
										</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0)"><i class="fa fa-building-o"></i> <span class="title">Report Management</span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li>
										<a href="login_login.html">
											<span class="title"> Login Form </span>
										</a>
										<ul class="sub-menu">
											<li>
												<a href="table_basic.html">
													<span class="title">Basic Tables</span>
												</a>
											</li>
										</ul>
									</li>
									<li>
										<a href="login_login.html?box=register">
											<span class="title"> Registration Form </span>
										</a>
									</li>
									<li>
										<a href="login_login.html?box=forgot">
											<span class="title"> Forgot Password Form </span>
										</a>
									</li>
									<li>
										<a href="login_lock_screen.html">
											<span class="title">Lock Screen</span>
										</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0)"><i class="fa fa-cog"></i> <span class="title">Systemt Management</span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li>
										<a href="login_login.html">
											<span class="title"> Login Form </span>
										</a>
									</li>
									<li>
										<a href="login_login.html?box=register">
											<span class="title"> Registration Form </span>
										</a>
									</li>
									<li>
										<a href="login_login.html?box=forgot">
											<span class="title"> Forgot Password Form </span>
										</a>
									</li>
									<li>
										<a href="login_lock_screen.html">
											<span class="title">Lock Screen</span>
										</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="javascript:void(0)"><i class="fa fa-user"></i> <span class="title">User Management</span><i class="icon-arrow"></i> </a>
								<ul class="sub-menu">
									<li>
										<a href="login_login.html">
											<span class="title"> Login Form </span>
										</a>
									</li>
									<li>
										<a href="login_login.html?box=register">
											<span class="title"> Registration Form </span>
										</a>
									</li>
									<li>
										<a href="login_login.html?box=forgot">
											<span class="title"> Forgot Password Form </span>
										</a>
									</li>
									<li>
										<a href="login_lock_screen.html">
											<span class="title">Lock Screen</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
						<!-- end: MAIN NAVIGATION MENU -->
					</div>
					<!-- end: SIDEBAR -->
				</div>
				<div class="slide-tools">
					<div class="col-xs-6 text-left no-padding">
						<a class="btn btn-sm status" href="#">
							Status <i class="fa fa-dot-circle-o text-green"></i> <span>Online</span>
						</a>
					</div>
					<div class="col-xs-6 text-right no-padding">
						<a class="btn btn-sm log-out text-right" href="login_login.html">
							<i class="fa fa-power-off"></i> Log Out
						</a>
					</div>
				</div>
			</nav>
			<!-- end: PAGESLIDE LEFT -->