<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();?>
<!-- start: PAGESLIDE RIGHT -->
			<div id="pageslide-right" class="pageslide slide-fixed inner">
				<div class="right-wrapper">
					<div class="notifications">
						<div class="pageslide-title" style="text-align: center;">
							 <?php echo $tr->translate('REPORT_AND_STYLE') ?>
						</div>
						<ul class="pageslide-list">
							<li>
								<a href="javascript:void(0)">
									<span class="label"><i class="fa fa-building-o"></i></span> <span class="message"> <?php echo $tr->translate('MENU_AND_TABLE_LIST_REPORT') ?></span>
								</a>
							</li>
							<li>
								<a href="javascript:void(0)">
									<span class="label"><i class="fa fa-building-o"></i></span> <span class="message"> <?php echo $tr->translate('SALE_REPORT') ?></span>
								</a>
							</li>
							<li>
								<a href="javascript:void(0)">
									<span class="label"><i class="fa fa-building-o"></i></span> <span class="message"> <?php echo $tr->translate('INVENTORY_REPORT') ?></span>
								</a>
							</li>
							<li>
								<a href="javascript:void(0)">
									<span class="label"><i class="fa fa-building-o"></i></span> <span class="message"> <?php echo $tr->translate('DS_REPORT') ?></span>
								</a>
							</li>
						</ul>
					</div>
					<!-- 
					<div class="hidden-xs" id="style_selector">
						<div id="style_selector_container">
							<div class="pageslide-title">
								Style Selector
							</div>
							<div class="box-title">
								Choose Your Layout Style
							</div>
							<div class="input-box">
								<div class="input">
									<select name="layout" class="form-control">
										<option value="default">Wide</option><option value="boxed">Boxed</option>
									</select>
								</div>
							</div>
							<div class="box-title">
								Choose Your Header Style
							</div>
							<div class="input-box">
								<div class="input">
									<select name="header" class="form-control">
										<option value="fixed">Fixed</option><option value="default">Default</option>
									</select>
								</div>
							</div>
							<div class="box-title">
								Choose Your Sidebar Style
							</div>
							<div class="input-box">
								<div class="input">
									<select name="sidebar" class="form-control">
										<option value="fixed">Fixed</option><option value="default">Default</option>
									</select>
								</div>
							</div>
							<div class="box-title">
								Choose Your Footer Style
							</div>
							<div class="input-box">
								<div class="input">
									<select name="footer" class="form-control">
										<option value="default">Default</option><option value="fixed">Fixed</option>
									</select>
								</div>
							</div>
							<div class="box-title">
								10 Predefined Color Schemes
							</div>
							<div class="images icons-color">
								<a href="#" id="default"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-1.png" alt="" class="active"></a>
								<a href="#" id="style2"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-2.png" alt=""></a>
								<a href="#" id="style3"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-3.png" alt=""></a>
								<a href="#" id="style4"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-4.png" alt=""></a>
								<a href="#" id="style5"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-5.png" alt=""></a>
								<a href="#" id="style6"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-6.png" alt=""></a>
								<a href="#" id="style7"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-7.png" alt=""></a>
								<a href="#" id="style8"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-8.png" alt=""></a>
								<a href="#" id="style9"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-9.png" alt=""></a>
								<a href="#" id="style10"><img src="<?php echo $this->baseUrl();?>/assetss/images/color-10.png" alt=""></a>
							</div>
							<div class="box-title">
								Backgrounds for Boxed Version
							</div>
							<div class="images boxed-patterns">
								<a href="#" id="bg_style_1"><img src="<?php echo $this->baseUrl();?>/assetss/images/bg.png" alt=""></a>
								<a href="#" id="bg_style_2"><img src="<?php echo $this->baseUrl();?>/assetss/images/bg_2.png" alt=""></a>
								<a href="#" id="bg_style_3"><img src="<?php echo $this->baseUrl();?>/assetss/images/bg_3.png" alt=""></a>
								<a href="#" id="bg_style_4"><img src="<?php echo $this->baseUrl();?>/assetss/images/bg_4.png" alt=""></a>
								<a href="#" id="bg_style_5"><img src="<?php echo $this->baseUrl();?>/assetss/images/bg_5.png" alt=""></a>
							</div>
							<div class="style-options">
								<a href="#" class="clear_style">
									Clear Styles
								</a>
								<a href="#" class="save_style">
									Save Styles
								</a>
							</div>
						</div>
						<div class="style-toggle open"></div>
					</div> -->
				</div>
			</div>
			<!-- end: PAGESLIDE RIGHT -->