<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage ();
$form = $this->form;
?>
<script src="<?php echo $this->baseUrl();?>/active.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu");
	var g = document.getElementById("menu_group");
	d.className = d.className + " active open";
	g.className = g.className + " active open";
});
//-->
</script>
<style>
<!--
#panel-body {
	padding: 0 !important;
}

.col-md-12 {
	padding: 0 !important;
}

input[type=checkbox] {
	*opacity: 1 !important;
}

.form-group {
	padding: 0;
}

.form-horizontal .form-group {
	margin: 0;
	padding: 10px 0;
}
-->
</style>
<div class="main-wrapper">
	<form role="form" class="form-horizontal" id="form"
		enctype="multipart/form-data" method="post">
		<!-- start: MAIN CONTAINER -->
		<div class="main-container inner">
			<!-- start: PAGE -->
			<div class="main-content">
				<!-- end: SPANEL CONFIGURATION MODAL FORM -->
				<div class="container">
					<!-- start: BREADCRUMB -->
					<div class="row" style="margin-top: 5px;"></div>
					<!-- end: BREADCRUMB -->
					<div class="col-md-12">
						<div class="errorHandler alert alert-danger no-display">
							<i class="fa fa-times-sign"></i> You have some form errors.
							Please check below.
						</div>
						<div class="successHandler alert alert-success no-display">
							<i class="fa fa-ok"></i> Your form validation is successful!
						</div>
					</div>
					<!-- start: PAGE CONTENT -->
					<div class="row">
						<div class="col-sm-12">
							<!-- start: TEXT FIELDS PANEL -->
							<div class="panel panel-white">
								<div class="panel-heading">
									<div class="" style="float: right;">
										<button type="submit" class="btn btn-primary">
											<i class="fa fa-edit"></i> Eidt
										</button>
										<button type="button" class="btn btn-primary panel-refresh">
											<i class="fa fa-save"></i> Save
										</button>
										<button type="button" class="btn btn-primary">
											<i class="glyphicon glyphicon-log-in"></i> Save New
										</button>
										<a href="<?php echo $this->baseUrl();?>/menu"><button
												type="button" class="btn btn-red">
												<i class="fa fa-times"></i> Eixt
											</button></a>
									</div>
								</div>
								<div class="panel-body">
									<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("COLOR_DISCRIPTION")?>
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('color_discription');?>
												</div>

										</div>
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_SIZE")?> 
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('item_size');?>
												</div>
										</div>
									</div>
									<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_WEIGHT")?>
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('item_weight');?>
												</div>

										</div>
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_VOLUME")?> 
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('item_volume');?>
												</div>
										</div>
									</div>
									<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_WIDTH")?>
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('itme_width');?>
												</div>

										</div>
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_HEIGHT")?> 
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('itme_height');?>
												</div>
										</div>
									</div>
									<div class="col-sm-12" style="padding: 0;">
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_LENGTH")?>
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('itme_length');?>
												</div>

										</div>
										<div class="form-group col-sm-6">
											<label class="col-sm-4 control-label">
													<?php echo $tr->translate("ITEM_COLOR")?> 
												</label>
											<div class="col-sm-8">
													<?php echo $form->getElement('item_color');?>
												</div>
										</div>
									</div>
									<div class="col-sm-6" style="padding: 0;">
										
									</div>
									<div class="form-group col-sm-6">
												<label class="col-sm-4 control-label" for="form-field-1">
													<?php echo $tr->translate("IMAGE")?>  <span class="symbol required"></span>
												</label>
												<div class="col-sm-8">
													<div class="fileupload fileupload-new" data-provides="fileupload">
														<div class="fileupload-new thumbnail"><img src="" alt=""/>
														</div>
														<div class="fileupload-preview fileupload-exists thumbnail"></div>
														<div>
															<span class="btn btn-light-grey btn-file"><span class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span><span class="fileupload-exists"><i class="fa fa-picture-o"></i> Change</span>
																<input type="file" name="photo">
															</span>
															<a href="#" class="btn fileupload-exists btn-light-grey" data-dismiss="fileupload">
																<i class="fa fa-times"></i> Remove
															</a>
														</div>
													</div>
												</div>
											</div>
								</div>
								<div class="col-md-12">
												<div class="panel-body table-responsive" id="panel-body">
													<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
														<thead>
															<tr>
																<th>ITEM_CODE</th>
																<th>BRANCH</th>
																<th class="hidden-xs">DISCRIPTION</th>
																<th>SECOND_LANGAUGE</th>
																<th>AVG.COST</th>
																<th>HANDON</th>
																<th>STOCK_UNIT</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>001</td>
																<td> 001</td>
																<td>tiger can</td>
																<td></td>
																<td>1.000</td>
																<td> 199.000</td>
																<td>CAN</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
				<!-- end: MAIN CONTAINER -->
				<div id="readNote">
					<div class="noteWrap col-md-8 col-md-offset-2">
						<div class="panel panel-note">
							<div class="e-slider owl-carousel owl-theme">
								<div class="item">
									<div class="panel-heading"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
	function SaveData(){
		div = document.getElementById("refreshdiv");
		div.submit();
	}
</script>