<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage(); $form = $this->form;?>
<script type="text/javascript">
<!--
$(document).ready(function(){
	var d = document.getElementById("menu_table");
	d.className = d.className + " active open";
});
//-->
</script>
		<div class="main-wrapper">
			<!-- start: MAIN CONTAINER -->
			<div class="main-container inner">
				<!-- start: PAGE -->
				<div class="main-content">
					<!-- end: SPANEL CONFIGURATION MODAL FORM -->
					<div class="container">
						<!-- start: BREADCRUMB -->
						<div class="row">
							<div class="col-md-12">
								<ol class="breadcrumb" style="background: #FFF;">
									<li style="padding-left: 10px;">
										<a href="#" style="font-size: 15px;">
											<?php echo $tr->translate("DASHBOARD")?>
										</a> 
									</li>
									<li style="padding-left: 10px;">
										<a href="#" style="font-size: 15px;">
											<?php echo $tr->translate("TABLES")?>
										</a> 
									</li>
								</ol>
							</div>
						</div>
						<!-- end: BREADCRUMB -->
						<!-- start: PAGE CONTENT -->
						<div class="row">
							<div class="col-sm-12">
								<!-- start: TEXT FIELDS PANEL -->
								<div class="panel panel-white">
									<div class="panel-heading">
										<h4 class="panel-title">Text <span class="text-bold">Fields</span></h4>
										<div class="panel-tools">
											<div class="dropdown">
												<a data-toggle="dropdown" class="btn btn-xs dropdown-toggle btn-transparent-grey">
													<i class="fa fa-cog"></i>
												</a>
												<ul class="dropdown-menu dropdown-light pull-right" role="menu">
													<li>
														<a class="panel-collapse collapses" href="#"><i class="fa fa-angle-up"></i> <span>Collapse</span> </a>
													</li>
													<li>
														<a class="panel-refresh" href="#">
															<i class="fa fa-refresh"></i> <span>Refresh</span>
														</a>
													</li>
													<li>
														<a class="panel-expand" href="#">
															<i class="fa fa-expand"></i> <span>Fullscreen</span>
														</a>
													</li>
													<li>
														<a class="panel-expand" href="#">
															<i class="fa fa-expand"></i> <span>Fullscreen</span>
														</a>
													</li>
												</ul>
											</div>
										</div>
									</div>
									<div class="panel-body">
										<form role="form" class="form-horizontal">
											<div class="form-group">
												<label class="col-sm-2 control-label" for="form-field-1">
													<?php echo $tr->translate("NAME")?>
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('name');?>
												</div>
												<label class="col-sm-2 control-label" for="form-field-2">
													<?php echo $tr->translate("PASSWORD")?>
												</label>
												<div class="col-sm-4">
													<?php echo $form->getElement('password');?>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-9">
												</div>
												<div class="col-sm-3" style="float: right;">
													<button type="button" class="btn btn-primary"><i class="fa fa-save"></i> Save New</button>
													<button type="button" class="btn btn-primary"> <i class="fa fa-save"></i> Save </button>
												</div>
											</div>
											
										</form>
									</div>
								</div>
								<!-- end: TEXT FIELDS PANEL -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- end: SUBVIEW SAMPLE CONTENTS -->
		</div>